language: cpp
compiler:
- clang
- gcc
before_install:
- sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
- sudo apt-get update -qq
- sudo apt-get install libosmesa6-dev
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
script: ./tests/run-tests.sh
after_success:
- sudo apt-get --no-install-recommends install doxygen
- git clone https://github.com/iauns/travis-doxy-helper ./doxy-helper
- ./doxy-helper/update-doxygen.sh ./.dox ./dox-repo https://github.com/iauns/cpm-gl-platform
branches:
  only:
  - master
env:
  global:
    secure: Bo0BqAV2rRPReLRsF62X7yBCbgCvqdwa5aXnL6drYf1/TkoBKYkCyOV2TxIFM/pgPXmeh1vfW0EB06IAfTLn56OqIWIDVFnRZbTslcoNeiOfmCAv9tufUwde9ui53ISLgtIkuKgL1IkpEevupJkSOH5Z4d4AvaIiPc+0WFktaIc=
